Neural Network: Experiment - 1: Introduction to pytorch

Hit and trials on different functions, basically experiments

In [17]:
# Explore the tools with different options like

# 1. Installation
# 2. Tensor creation deletion
# 3. Tensor manipulation

In [18]:
# Code by Bhavy Kharbanda
# Sap Id: 500082531 

In [19]:
import torch as th
import numpy as np

In [20]:
# Taking matrices directly as tensor objects
tensor1 = th.tensor([[2, 3, 4], [4, 5, 6]])
print("Matrix 1: \n", tensor1)

tensor2 = th.tensor([[5, 6, 7], [7, 8, 9]])
print("Matrix 2: \n", tensor2)


Matrix 1: 
 tensor([[2, 3, 4],
        [4, 5, 6]])
Matrix 2: 
 tensor([[5, 6, 7],
        [7, 8, 9]])


In [21]:
sum = tensor1 + tensor2
print("sum is: \n", sum)

sum is: 
 tensor([[ 7,  9, 11],
        [11, 13, 15]])
