Neural Network: Experiment - 1: Introduction to pytorch

Upper and lower traiangle of matrices.

In [1]:
# Explore the tools with different options like

# 1. Installation
# 2. Tensor creation deletion
# 3. Tensor manipulation

In [2]:
# Code by Bhavy Kharbanda
# Sap Id: 500082531 

In [3]:
import torch as th
import numpy as np

In [4]:
# list(map(int, input().split())): It splits all the values added by the user in a single row, so each character is taken as an individual after the space.
# np.array(entries).reshape(row, col): It reshapes all the entries in the size of row and column given by the user.


In [5]:
# Taking user input for matrix 1:
row1 = int(input("Enter the number of rows for matrix1: "))
col1 = int(input("Enter the number of columns for matrix1: "))
  
print("Enter the entries in a single line: ")

values = list(map(int, input().split()))
  
# For printing the matrix
matrix1 = np.array(values).reshape(row1, col1)
print(matrix1)


Enter the entries in a single line: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# Converting the matrices to tensor objects:
tensor1 = th.tensor(matrix1)

In [13]:
# Printing the upper triangle 
ut = th.triu(tensor1, 1)
print(ut)

tensor([[0, 2, 3],
        [0, 0, 6],
        [0, 0, 0]], dtype=torch.int32)


In [15]:
# Printing the upper triangle + diagonal
ut = th.triu(tensor1, 0)
print(ut)

tensor([[1, 2, 3],
        [0, 5, 6],
        [0, 0, 9]], dtype=torch.int32)


In [16]:
# Considering the upper diagonal of the main diagonal
ut = th.triu(tensor1, 2)
print(ut)

tensor([[0, 0, 3],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
